#!/usr/bin/python -tt

#HOW TO RUN python
#rm Date_diff_2.py; rm All_id.txt_date_diff
#python ID_type_name_assign_v3.py test5
#python ID_type_name_assign_v3.py n_id
#head t100c.txt_date_diff

import re
import sys


# Reads line by line,humble does not lock memory.
def file_work(filename):
  f = open(filename, 'rU')
  for line in f:
    columns = line.strip().split("|")
    id_column = (columns[4])
    CSP_9 = re.search(r'^[A-Za-z@0-9#\*]{8}[0-9]$', id_column)
    RIC = re.search(r'\.', id_column)
    XQ = re.search(r'^XQ|^xq', id_column)
    ISIN = re.search(r'^[A-Za-z]{2}\w{9}[0-9]$', id_column)
    TCR = re.search(r'^[A-Za-z]{1,5}$', id_column)
    XS = re.search(r'^XS|^xs', id_column)
    QCK = re.search(r'^[0-9]{4}$', id_column)
    SDL = re.search(r'^[0-9BCDFGHJKLMNPQRSTVWXYZbcdfghjklmnpqrstvwxyz]{6}[0-9]$', id_column)
    SDL_6 = re.search(r'^[0-9BCDFGHJKLMNPQRSTVWXYZbcdfghjklmnpqrstvwxyz]{6}$', id_column)
    QCK_5 = re.search(r'^[0-9]{5}$', id_column)
    TCR_C = re.search(r'^[A-Za-z]{1,5}[0-9]{1,2}$', id_column)
    CSP_8 = re.search(r'^[A-Za-z@0-9#\*]{8}$', id_column)
    ETS = re.search(r'^[0-9]{5,6}[A-Za-z]{1}$', id_column)
    RDET = re.search(r'^[A-Z]{6}$', id_column)
    if CSP_9:
      out = "CSP_9" + "|" + str(line)
      outf = open(filename + "_" + "CSP_9", 'a')
      outf.write(out)
    elif RIC:
      out = "RIC" + "|" + str(line)
      outf = open(filename + "_" + "RIC", 'a')
      outf.write(out)
    elif XQ:
      out = "XQ" + "|" + str(line)
      outf = open(filename + "_" + "XQ", 'a')
      outf.write(out)
    elif ISIN:
      out = "ISIN" + "|" + str(line)
      outf = open(filename + "_" + "ISIN", 'a')
      outf.write(out)
    elif TCR:
      out = "TCR" + "|" + str(line)
      outf = open(filename + "_" + "TCR", 'a')
      outf.write(out)
    elif XS:
      out = "XS" + "|" + str(line)
      outf = open(filename + "_" + "XS", 'a')
      outf.write(out)
    elif QCK:
      out = "QCK" + "|" + str(line)
      outf = open(filename + "_" + "QCK", 'a')
      outf.write(out)
    elif SDL:
      out = "SDL" + "|" + str(line)
      outf = open(filename + "_" + "SDL", 'a')
      outf.write(out)
    elif SDL_6:
      out = "SDL_6" + "|" + str(line)
      outf = open(filename + "_" + "SDL_6", 'a')
      outf.write(out)
    elif QCK_5:
      out = "QCK_5" + "|" + str(line)
      outf = open(filename + "_" + "QCK_5", 'a')
      outf.write(out)
    elif TCR_C:
      out = "TCR_C" + "|" + str(line)
      outf = open(filename + "_" + "TCR_C", 'a')
      outf.write(out)
    elif CSP_8:
      out = "CSP_8" + "|" + str(line)
      outf = open(filename + "_" + "CSP_8", 'a')
      outf.write(out)
    elif ETS:
      out = "ETS" + "|" + str(line)
      outf = open(filename + "_" + "ETS", 'a')
      outf.write(out)
    elif RDET:
      out = "RDET" + "|" + str(line)
      outf = open(filename + "_" + "RDET", 'a')
      outf.write(out)
    else:
      out = "REM" + "|" + str(line)
      outf = open(filename + "_" + "REM", 'a')
      outf.write(out)
  f.close()
  outf.close()

def main():
  file_work(sys.argv[1])

# This is the standard boilerplate that calls the main() function.
if __name__ == '__main__':
  main()
